[WIP] Handle lists of available tsos and business processes
gridsuite/cgmes-boundary-server pull request #11
Opened 2021-04-14 08:57 UTC by FranckLecuyer

2021-04-20 11:59 UTC, ChamseddineBhd requested changes

2021-04-21 12:17 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/cgmes/boundary/server/CgmesBoundaryService.java
> +            BusinessProcessesListEntity entity = new BusinessProcessesListEntity(BUSINESS_PROCESS_LIST_NAME, buf);
Yes

2021-04-21 13:54 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/cgmes/boundary/server/CgmesBoundaryController.java
> +            throw new PowsyblException("No available list of tsos");
empty set is now returned

2021-04-21 13:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/cgmes/boundary/server/CgmesBoundaryController.java
> +    }
Done

2021-04-21 13:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/cgmes/boundary/server/CgmesBoundaryController.java
> +    }
Done

2021-04-21 13:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/cgmes/boundary/server/CgmesBoundaryController.java
> +            throw new PowsyblException("No available list of business processes");
Done

2021-04-22 09:24 UTC, JacquesBorsenberger approved these changes

2021-04-22 09:42 UTC, ChamseddineBhd approved these changes

2021-04-22 09:44 UTC, merged